### ISSUE TITLE
Simplified title

### ISSUE THREAD

**Issue by andreiborisov** [pure-fish/pure#115]
I'd like to open a discussion about possibility of adding customisations or making changes to the title.

From what I can grasp from [original ZSH prompt](https://github.com/sindresorhus/pure/blob/master/pure.zsh), our current title doesn't behave the same.

Currently I'm using simplified version of the title:
```
function fish_title \
    --description "Set title to current folder and shell name" \
    --argument-names last_command

    set --local current_folder (_pure_parse_directory)

    set --local prompt
    if test -z "$last_command"
        set prompt "$current_folder"
    else
        set prompt "$last_command"
    end

    echo $prompt
end
```

It doesn't print shell name and only prints invoked command when command is running.

Is it useful to print shell name? Seems distracting and unnecessary. The same goes for double printing command name when command is running.

**Comment by edouard-lopez** [comment]
Feature-wise, I reckon we [differ a bit from the zsh version](https://github.com/sindresorhus/pure#options) over time. However, recent PRs help reduce the gap :clap: 

Our current [`fish_title`](https://github.com/rafaelrinaldi/pure/blob/master/fish_title.fish) code isn't satisfactory (IMHO) and furthermore differ from the original one. 

### Title
Looking at the original pure, the title is pretty simple:

1. [SSH hostname](https://github.com/sindresorhus/pure/blob/c985b1979abfaf7860e7cc6ebf5d91eaeaca142e/pure.zsh#L81) ;

       print -n $opts $'\e]0;'${hostname}${2}$'\a'

1. [Currenty working directory](https://github.com/sindresorhus/pure/blob/c985b1979abfaf7860e7cc6ebf5d91eaeaca142e/pure.zsh#L98) ;

       prompt_pure_set_title 'ignore-escape' "$PWD:t: $2"

1. Excuted command (`$2`)

### Customization

As I'm using `tmux` in `yakuake`, a quake-like terminal and never really pay attention to the tab/window title (I had to use `gnome-terminal` to test _fish_title.fish_ :)

Your version is fine by me, but if other want to chime cc @rafaelrinaldi @jorgebucaran  @filipebarros

**Comment by schrodincat** [comment]
1. It seems useful to show SSH hostname on remote connections (similarly how we do it on the main prompt). I would add it.
2. Yeah, my version is too simplistic. It's still useful to have directory when executing command.
3. I don't know if original prompt shows shell name, but in my opinion, it's unnecessary. I mean, user probably know, what shell he uses. There also a question whether we should print last executed command with arguments (`$last_command`) or last job that was put to the foreground (`status current-command`)? I'd say the later one isn't terribly useful since it's not updated live while command being executed, only when it's invoked.

**Comment by edouard-lopez** [comment]
1. I'm ok with this, moreover, SSH information should be consistent between the title and prompt.
2. Let user decide with a feature flag `pure_title_show_current_working_dir`
3. Shell name might be useful when working with multiple terminal windows but I prefer not to encourage that. For the moment, I'm in favour to remove it and see if people request it. Displaying the last invoked command is IMHO more valuable.

**Comment by rafaelrinaldi** [comment]
I have also noticed a few times that the title behavior could use some work; they are not very useful as of now. Happy to review a PR with your proposal @schrodincat!

**Comment by schrodincat** [comment]
> Happy to review a PR with your proposal!

☺️ I’m planing to work on it next week

**Comment by edouard-lopez** [comment]
I'm closing this as it's pretty 4 years old and no PR was submitted. Meanwhile, we introduced `pure_shorten_window_title_current_directory_length` settings in https://github.com/pure-fish/pure/releases/tag/v4.5.0. 

#### No shortening with `0`
```shell
❯ set --universal --export pure_shorten_window_title_current_directory_length 0
```
![image](https://github.com/pure-fish/pure/assets/1212392/7cc22e75-35aa-44a4-830a-2f08adcf0514)


#### Custom shortening
```shell
❯ set --universal --export pure_shorten_window_title_current_directory_length 1
```
![image](https://github.com/pure-fish/pure/assets/1212392/c916695b-b905-48b3-9820-40ffcb12a310)
