### ISSUE TITLE
Show `username@host` if inside a container

### ISSUE THREAD

**Issue by edouard-lopez** [pure-fish/pure#241]
**related:** #214

---

* Zsh Feature to [display `username@host` when inside a container](https://github.com/sindresorhus/pure/blob/8ec575c886c8bb33a87f80b9710ee5e379a0b589/pure.zsh#L688). 
* Zsh [Pull-request and explaination](https://github.com/sindresorhus/pure/pull/564) 

~Testing this feature will prove challenging~ we run test in container so it's cool

**Comment by edouard-lopez** [comment]
```fish
function _pure_is_inside_container
  if (test -r /proc/1/cgroup
     -a cat /proc/1/cgroup \
     | string match \
         --quiet \
         --entire \
         --regex '(lxc|docker)'
     ) -o $container = "lxc" 
    echo 'in container'
end
```

**Comment by jorgebucaran** [comment]
@edouard-lopez Useless use of `cat`.

```fish
string match --quiet --entire --regex '(lxc|docker)' </proc/1/cgroup
```

**Comment by edouard-lopez** [comment]
done #271
