### ISSUE TITLE
Request: Ownership Transfer

### ISSUE THREAD

**Issue by edouard-lopez** [pure-fish/pure#249]
### Project's Background

* @rafaelrinaldi started the project in October 2015 and I'm grateful for it :clap: (see a5d0721d4f584f7d4cd6734c03b190de09d5ef01)
* I started to contribute to on early December 2015 (see 72f0e00ef9d5eaf8c3f28bc5341939d945c40671)
* @schrodincat/@andreiborisov started to contribute b09bfdcd132abaebb079c92f718cdcfd19cd66cb
* plenty of other persons contributed with issues or PRs :clap: 

Rafael has been a great help to enter the project but sadly his involvement in the project has dwindled over time. Andrei was also a great help but decided to focus other project and left this summer.

### What I'm Doing?
Since joining the project, I massively contribute to the project by:
* adding new features :rocket: ;
* adding lots of tests (now at ~170) :robot: ;
* configuring CI (twice, thanks Travis 😑) ;
* onboarding new contributors :technologist:  ;
* triaging issues :bug: ;
* merging PRs :twisted_rightwards_arrows: ;
* defining [code convention](CONTRIBUTING.md) :page_with_curl: ;
* releasing versions :package: 
* etc.

Like [contributed a lot](https://github.com/rafaelrinaldi/pure/graphs/contributors):
```
#1 edouard-lopez: 395 commits    6,275 ++    4,232 --
#2 rafaelrinaldi:  46 commits       540 ++      312 --
#3 boyeborg:         7 commits        42 ++        30 --
#4 benedictleejh:   7 commits        59 ++         4 --
```
@andreiborisov/schrodincat [your stats](https://github.com/rafaelrinaldi/pure/graphs/contributors) are missing, it might be due to your username change, not sure.

### Why This Request?

Transferring ownership is motivated by the fact that I'm the main contributor and the sole active maintainer. However, my hands are tied as I don't have the privileges to manage the project from top to bottom, _e.g._ to:
* add new maintainers to remove single point of failure ;
* access project's settings ;
* configuring PR template ;
* updating project's About and keywords to get more visibility ;
* setting up an open collective (like we did in [LessPass](https://github.com/lesspass/lesspass/#contributors)).

As a contributor and maintainer of various open-source projects, I know how difficult it is to stay focus and keep allocating time to them.

### Community

First time I do such request, might have done some missteps. Be kind :hugs:  

### @rafaelrinaldi 

Would you be kind enough to [transfer ownership](<https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account>) to me, so I can take up the torch of the project?

**Comment by rafaelrinaldi** [comment]
Thanks for bringing this up! I am more than willing to change our model but I think it would make more sense for us to setup an org instead so it is no longer tied to a specific maintainer. Thoughts?

**Comment by edouard-lopez** [comment]
Organization is great!
It will give more flexibility to add contributors or add others related repo (e. g. @andreiborisov docker images ?)

**Comment by jorgebucaran** [comment]
Some ideas: 
1. `@pureforfish`
2. `@pure4fish`
3. `@getpure`
4. `@puregoesfish` 
5. `@puregonefishin`
6. `@realpurefish`

**Comment by edouard-lopez** [comment]
I like
2. `@pure4fish`
3. `@getpure`
I was thinking of
7. `@pure`
8. `@pure-prompt`

**Comment by jorgebucaran** [comment]
I think the name of the organization should suggest that this is a Fish project, so let's please avoid something generic like `@pure` (which is not even available) or `@getpure` (I've edited my post to reflect this realization).

**Comment by edouard-lopez** [comment]
Apparently we can do `pure.fish`. Not a fan of `@getpurefish`
I'm updating my vote.

**Comment by jorgebucaran** [comment]
Just fyi, organization names can't contain any special characters, so `@pure.fish` will become `@pure-fish`.

**Comment by edouard-lopez** [comment]
I created a [`pure-fish` organization](https://github.com/pure-fish) and send you all ownership invitation, so we can continue.

**Comment by jorgebucaran** [comment]
Thank you, @edouard-lopez. Now, it's just a matter for @rafaelrinaldi to accept the invitation and transfer the repository to the organization.

**Comment by rafaelrinaldi** [comment]
Happy to do this, folks! Thanks so much for your interest and for the willingness to maintain the project. It started as a weekend side project but you all made it much better!

@edouard-lopez I don't see the request for the transfer though? Can you try sending me again?

**Comment by jorgebucaran** [comment]
@rafaelrinaldi What he sent you was an invitation to join @pure-fish, which should've landed in your email. You should be able to view it on the [organization page](https://github.com/pure-fish) too. 

>  I don't see the request for the transfer though?

There's no request for transfer, you can find instructions to transfer it yourself [here](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository).

**Comment by rafaelrinaldi** [comment]
Joined the org from the email. Let me know if anything else is needed from
my end.

**Comment by jorgebucaran** [comment]
Welcome aboard, @rafaelrinaldi. Yes, now you can transfer the repo to the organization.
