### ISSUE TITLE
Options to choose when to display the current user and/or host

### ISSUE THREAD

**Issue by pacien** [pure-fish/pure#254]
… the same way they are automatically displayed when in an SSH session.

This is particularly useful when running `sudo -s` on a remote host, which causes the user and host indicator to disappear.
This indicator is also useful when running that command locally.

**Comment by edouard-lopez** [comment]
Related to #241 #117 #214

**Comment by edouard-lopez** [comment]
@pacien #271 added support for user/host display in docker/lxc container. 

That's not a feature I aim to support, but you can play with `pure_symbol_prompt` variable, _e.g._:

	set pure_symbol_prompt "$USER ❯"
