### ISSUE TITLE
Displaying conda/virtualenv env name has incorrect spacing

### ISSUE THREAD

**Issue by officerats** [pure-fish/pure#276]
## Env

**Pure**

    3.5.0

**Fish**

    3.1.2

**OS/distribution**

    MacOS, using nix to build my working environment

Displaying conda env/virtual env name kinda ruins prompt line formatting for me.

My set up on version 3.5.0 is as follows:

```
set --universal pure_enable_single_line_prompt true
set --universal pure_show_prefix_root_prompt true
set --universal pure_begin_prompt_with_current_directory false
set --universal pure_threshold_command_duration 60
```
and my prompt looks like

	~test  ❯

instead of expected

	~ test ❯

Note there's 
- a space missing after current dir
- double space between conda env name and pure symbol prompt, which can't been seen here because of Markdown formatting, but it's there

My random guess about double space is it happens because there's explicit `$space` after `$virtualenv \` in [_pure_prompt
](https://github.com/pure-fish/pure/blob/081f81cd6c32a44f92c0c98cc93d64d035f5dddd/functions/_pure_prompt.fish#L23). I don't really get why there's missing space between current dir and conda env name though. My guess might be wrong though.

**Comment by ajgrover** [comment]
I'm also having this issue, or at least a related one. on fish 3.2.0 and pure 3.5.0 and my prompt with the virtualenv activated looks like this:

`~/Developer/repo mastervenv  ❯`

no space between the branch and venv names and two spaces after the venv name.

**Comment by edouard-lopez** [comment]
That's a bug indeed, as it's non-blocking it's a low priority but I'm available to review any PR on the matter.
My guess is that an extra space, or something else, come from conda/virtualenv.
