### ISSUE TITLE
type: Unknown option '--quiet'

### ISSUE THREAD

**Issue by wy15** [pure-fish/pure#277]
## Env

**Pure**

    4.1.0

**Fish**

    fish, version 3.2.0

**OS/distribution**

    macOS bigsur 11.2.2

**Error message**

    type: Unknown option '--quiet'

**Comment by Asheboy** [comment]
## Env

**Pure**

    `4.1.0`

**Fish**

    `fish, version 3.2.0`

**OS/distribution**

    ```Distributor ID: Neon
Description:    KDE neon User Edition 5.21
Release:        20.04
Codename:       focal
```
