### ISSUE TITLE
prompt character broken

### ISSUE THREAD

**Issue by the-aus** [pure-fish/pure#279]
## Env

**Pure**

    echo $pure_version
    
    4.1.0

**Fish**

    fish --version
    
    fish, version 3.1.2

**OS/distribution**

    lsb_release -a
    
    LSB Version:	1.4
    Distributor ID:	Arch
    Description:	Arch Linux
    Release:	rolling
    Codename:	n/a
    

`â¯` is what shows up.

here is a screenshot of the issue

![https://img.theaus.xyz/P6JgCIoa.png](https://img.theaus.xyz/P6JgCIoa.png)

installed with fisher

**Comment by jorgebucaran** [comment]
What does `echo $pure_symbol_prompt` tell you?

**Comment by the-aus** [comment]
it gives me `â¯` as an output

**Comment by the-aus** [comment]
i was able to fix this by running `set -u pure_symbol_prompt ❯`

not really sure how it got messed up. thanks for the help :)

p.s. i was able to get that character to copy from [here](https://github.com/pure-fish/pure/blob/master/conf.d/pure.fish)
