### ISSUE TITLE
Change git branch color

### ISSUE THREAD

**Issue by Lorenium** [pure-fish/pure#281]
## Env

**Pure**

    echo $pure_version

4.1.1

**Fish**

    fish --version

3.2.2

**OS/distribution**

    lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

My terminal background is the same color as the default git branch color and I wanna change it to something a little more opaque so that I can see it. How can I achieve this?

**Comment by edouard-lopez** [comment]
For the possibility, refer to the `conf.d/pure.fish` file:
https://github.com/pure-fish/pure/blob/9d17b2780165572bc6c181cd0e7c5d6dd13be5c1/conf.d/pure.fish#L23-L33

To set the config, try:

	set --universal pure_color_git_branch red

Then choose the color you want

**Comment by Lorenium** [comment]
Thanks a lot, got it visible at last. I highly suggest you add this to the readme as I suspect many people use dark-gray backgrounds and can't properly see the branch info.

**Comment by edouard-lopez** [comment]
There is a [Configuration section](https://github.com/pure-fish/pure#paintbrush-configuration) in the doc, the variable are in [pure.fish](https://github.com/pure-fish/pure/blob/master/conf.d/pure.fish)
