### ISSUE TITLE
[request] Is there anyway to have the following prompt: $tail on $git_branch

### ISSUE THREAD

**Issue by KarlWithK** [pure-fish/pure#292]
I was wondering if there were any way to have the following format? $dir_tail on $git_branch

Thank you.

**Comment by edouard-lopez** [comment]
You can customize `prompt_components` variable in [`~/.config/fish/functions/_pure_prompt_first_line.fish`](https://github.com/pure-fish/pure/blob/master/functions/_pure_prompt_first_line.fish#L24-L38), e.g.:

```doff
set prompt_components \
                $current_folder \
+              " on " \
                $prompt_git \
                $prompt_ssh \
                $prompt_container \
                $prompt_command_duration
```
