### ISSUE TITLE
Missing blank line between prompts?

### ISSUE THREAD

**Issue by gtalarico** [pure-fish/pure#293]
Screenshots appear to indicate there is a blank line between output and next prompt.
However in my terminal (iterm2 + terminal) output and next prompt are right against each other.

Is this expected? Are screenshots outdated?

I looked through configs and while I see the option to have compact prompt (set to false) I don't see anything on the extra line.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/9513968/190098779-8cf72017-efe5-418b-a379-297a668c153d.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/9513968/190098242-6fa5f34a-dfd1-4c37-aad7-9708710e7615.png">

Thank you for this beautiful theme.

## Env

**Pure**
4.1.1

**Fish**
fish, version 3.5.1

**OS/distribution**
MacOs 12.5.1

**Comment by edouard-lopez** [comment]
Thanks for spotting this!
That's a regression on the theme :S 
I probably don't have a test for this. I will keep you up-to-date when I fix it

**Comment by JosephHalter** [comment]
The bug still seem to be here to this day.

**Comment by edouard-lopez** [comment]
@gtalarico would you mind testing the PR #326 ?

```
fish install pure-fish/pure@fix/missing-blank-line-between-prompts-293
