### ISSUE TITLE
Prompt outputting _pure_is_inside_container 1

### ISSUE THREAD

**Issue by davgothic** [pure-fish/pure#300]
I just ran fisher update which upgraded to the latest version of this prompt and now my prompt is suffixed with `_pure_is_inside_container 1`.

I'm not within a docker container. I thought at first it was detecting my tmux session so opened a new terminal and it's doing the same there.

## Env

**Pure**

    4.1.1

**Fish**

    fish, version 3.5.1

**OS/distribution**

    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 22.04.1 LTS
    Release:        22.04
    Codename:       jammy

**Comment by ivakam** [comment]
Same thing here on endavour, latest fish

**Comment by edouard-lopez** [comment]
Could you check with [`4.2.3`](https://github.com/pure-fish/pure/releases/tag/v4.2.3)? I believe it was a debugging side-effect

    fisher install pure-fish/pure

**Comment by ivakam** [comment]
That does indeed seem to have fixed it.

**Comment by davgothic** [comment]
@edouard-lopez I can confirm this has fixed the issue. Thank you!
