### ISSUE TITLE
head: cannot open '/proc/1/sched' for reading: No such file or directory

### ISSUE THREAD

**Issue by 0-st** [pure-fish/pure#301]
Also prints `~ 2<user@host>2` instead of `~ user@host` when logged in over ssh.

The workaround in https://github.com/pure-fish/pure/issues/295#issuecomment-1269997370 works for hiding the `head: cannot open...` lines.

## Env

**Pure**

    4.2.3

**Fish**

    fish, version 3.5.1

**OS/distribution**

    LSB Version:    1.0
    Distributor ID: VoidLinux
    Description:    Void Linux
    Release:        rolling
    Codename:       void

**Comment by edouard-lopez** [comment]
### Degugging

Do you have `/proc/` directory in VoidLinux, I'm using it in both the [pid method](https://github.com/pure-fish/pure/blob/master/functions/_pure_detect_container_by_pid_method.fish) and the [cgroup method](https://github.com/pure-fish/pure/blob/master/functions/_pure_detect_container_by_cgroup_method.fish).

If so, could you share the output of:

    cat /proc/1/cgroup

### Container Detection Feature Flag

I will add a flag to disable the container detection feature

### Format over SSH

Would you mind opening a [new issue](https://github.com/pure-fish/pure/issues/new/) with more context of what you have/expect? This way I will be able to address it more efficiently.

**Comment by edouard-lopez** [comment]
Could you check the behavior of PR #302 ?

    ❯ fisher install pure-fish/pure@fix/301-voidlinux-container-detection

**Comment by faho** [comment]
It seems to me like _pure_detect_container_by_pid_method should test if /proc/1/sched exists before using it.

**Comment by edouard-lopez** [comment]
@faho I added the check
