### ISSUE TITLE
Is there any option in pure like truncation_length in starship? I want it to show last three parent folder.

### ISSUE THREAD

**Issue by 1999masih** [pure-fish/pure#336]
## Env

**Pure**

4.8.2

**Fish**

fish, version 3.6.2

**OS/distribution**

LSB Version:    n/a
Distributor ID: EndeavourOS
Description:    EndeavourOS Linux
Release:        rolling
Codename:       rolling

**Comment by edouard-lopez** [comment]
As I said on reddit, In [4.5.0](https://github.com/pure-fish/pure/releases/tag/v4.5.0) we introduced a shortening mechanism (not a truncate) based on `fish_prompt_pwd_dir_length`.

I will be happy to review and collaborate on a pull request ✌

**Comment by edouard-lopez** [comment]
## Config

### :computer:   Prompt shortening

| Option                                         | Default | Description                                                                                     |
| :--------------------------------------------- | :------ | :---------------------------------------------------------------------------------------------- |
| **`pure_truncate_prompt_current_directory_keeps`** | `0` | Truncate working directory path in prompt, but keeps the last to `n` components (`0` keep all)             |

### :window: Window's title shortening
| Option                                         | Default | Description                                                                                     |
| :--------------------------------------------- | :------ | :---------------------------------------------------------------------------------------------- |
| **`pure_truncate_window_title_current_directory_keeps`** | `0` |  Truncate working directory path in window title, but keeps the last to `n` components (`0` keep all) |

## How-to

refer to #307 and [pull request template](https://github.com/pure-fish/pure/blob/master/.github/pull_request_template.md)
