### ISSUE TITLE
Pure prompt contains newline in VSCode terminal

### ISSUE THREAD

**Issue by MrAru** [pure-fish/pure#341]
I'm not sure if this issue should be reported to pure or VSCode. As the title suggests, when using the Pure theme for fish shell in VSCode, it seems that there is a newline character after the prompt, separating the user input from the prompt content. This issue does not occur when using the original fish shell without any theme. Even if I set `pure_enable_single_line_prompt` to `true` it still occurs. Please refer to the screenshot below. Any suggestion could be helpful, thanks in advance.

pure theme

![屏幕截图 2024-01-17 122304](https://github.com/pure-fish/pure/assets/26517155/5cb524a5-941a-48d9-98f3-7f36a2e0aa9b)

pure theme, `set pure_enable_single_line_prompt true`

![屏幕截图 2024-01-17 122843](https://github.com/pure-fish/pure/assets/26517155/55a1dc64-a24e-40d2-9c84-5b7293aa4ede)

original fish theme

![屏幕截图 2024-01-17 123114](https://github.com/pure-fish/pure/assets/26517155/590e78e5-cef5-446b-9676-98e1e61cdc0a)

## Env

**Pure**

    4.8.3

**Fish**

    fish, version 3.3.1

**OS/distribution**

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.7 (Green Obsidian)
Release:        8.7
Codename:       GreenObsidian

**Comment by edouard-lopez** [comment]
Got something similar behavior as you when I'm not using `tmux` , but not when using other terminals


Terminal | Behavior | Screenshot | Comment
| --- | --- | --- | --- 
VSC (**without Tmux**) | ❌ | ![image](https://github.com/pure-fish/pure/assets/1212392/57f1f38d-532c-4292-b750-0a1ce74bfed6) | input on **different** line `❯`
VSCode with Tmux | ✅ | ![image](https://github.com/pure-fish/pure/assets/1212392/b7246902-fc80-4066-bd82-0ae680c66502) | input on `❯` line
GNOME Terminal<br>Version 3.49.92 for GNOME 45 | ✅ | ![image](https://github.com/pure-fish/pure/assets/1212392/506de5b4-7fe4-4cfb-85e3-db1c39078235) | input on `❯` line
Hyper `3.4.1` | ✅ | ![image](https://github.com/pure-fish/pure/assets/1212392/2fa76211-e1d2-437e-a6ae-e2c15f0666e3) | input on `❯` line
kitty 0.26.5 | ✅ | ![image](https://github.com/pure-fish/pure/assets/1212392/6b954db0-8a6c-443d-9e08-bfb781bb26f1) | input on `❯` line


## Conclusion
I would say it's a VSCode difference as multiple terminal application render in the same way

**Comment by edouard-lopez** [comment]
There is an issue on vcsode repo https://github.com/microsoft/vscode/issues/187185 and a solution on https://github.com/IlanCosman/tide/issues/433. The issue comes from `"terminal.integrated.shellIntegration.enabled` being enabled.

1. Disable this feature,
2. Kill the VSCode terminal (trash/bin icon on the top right of the panel)
3. Open terminal again

**Comment by MrAru** [comment]
@edouard-lopez Thanks for your help and this really fixed my issue! It seems that VSC does some magic with its shell integration procedure. I'm happy to close this issue now and enjoy this awesome theme 😄
